### ISSUE TITLE
Replace values of all fields AND preserve existing files

### ISSUE THREAD

**Issue by adehner** [Daniel-KM/CsvImportPlus#10]
I have an Omeka repository with thousands of items. Each item has at least one file attached. I would like to use this plugin to batch update item metadata in some of my collections. But when I try to do so, the files attached to my items are deleted.

What am I missing?
How can I preserve my files, but replace my existing metadata values with the values in a .csv file?

**Comment by Daniel-KM** [comment]
Could you give me the first two lines of your csv?

**Comment by adehner** [comment]
Action,Record Type,id,Collection Name,Title,Creator,Date,Description,Subject,Coverage,Type,Format,Language,Rights,Contributor,Local identifier
Replace,Item,154,RTEP-Whi - First Last Papers,Test title,"last, first",1910-12-31,He writes her concerning her comments about maps and papers.,maps; papers; writing,,letter,JPEG,English,Public domain,"last, first",xxxx-05-1446

**Comment by Daniel-KM** [comment]
I fixed it in version 2.3.1.

**Comment by adehner** [comment]
Excellent! I just tested to confirm, and it works great. Thanks Daniel.

**Comment by Daniel-KM** [comment]
I updated the fix to 2.3.2, so when there is an existing column for files, files will be removed or updated as before.
