### ISSUE TITLE
mixed records incorrect upload

### ISSUE THREAD

**Issue by AdrienneSerra** [Daniel-KM/CsvImportPlus#9]
I am trying to upload items, and then multiple files per item, but the import keeps creating the items with no files attached, and separate items with the files and no metadata. I have my CSV formatted just like test_manage_two.csv here's an image:
![samplecsvimport](https://cloud.githubusercontent.com/assets/6818486/21863699/77e2bb54-d80c-11e6-89ae-446b359b78e0.jpg)

**Comment by Daniel-KM** [comment]
Hi,

In the form, did you set the Dublin Core Identifier as identifier for the records in the csv (this is not the Omeka identifier, a simple number)? And have you tested the csv file test_manage_one.csv and test_manage_two.csv?

Sincerely,

Daniel Berthereau
Infodoc & Knowledge management
